### ISSUE TITLE
Exact dependencies here make the SDK less useful

### ISSUE THREAD

**Issue by kevinheavey** [Ellipsis-Labs/phoenix-v1#12]
phoenix-v1 is a program so it's good that it has exact dependencies, however phoenix-v1 is also used as a library in [phoenix-sdk-core](https://github.com/Ellipsis-Labs/phoenix-sdk/blob/master/rust/phoenix-sdk-core/Cargo.toml) so anyone using phoenix-sdk-core gets locked into a specific version of stuff like spl-token.

This probably requires a separate library crate for stuff that's common between the SDK and the program?

**Comment by jarry-xiao** [comment]
This is a really good point. Do you have a suggestion for a good way to do this? I'm happy to publish another crate without locking dependencies, but it would be good for that to live elsewhere -- maybe a dedicated branch?

**Comment by kevinheavey** [comment]
I would suggest just making a `phoenix-common` crate that has loose dependencies. `phoenix-sdk-core` would depend on `phoenix-common` and not on `phoenix-v1`. `phoenix-v1` would also depend on `phoenix-common`. If you want you could keep the exact dependencies in `phoenix-v1` even if they're not direct dependencies anymore

**Comment by jarry-xiao** [comment]
I think I'm okay with creating `phoenix-common` and having `phoenix-sdk` depend on `phoenix-common` but would prefer to keep the main program unchanged to ensure the build remain verifiable

**Comment by kevinheavey** [comment]
How would it break the verifiable build?

**Comment by jarry-xiao** [comment]
I'm concerned about Cargo pulling in updated versions of packages during the build. I think the Cargo.lock might help with this, but to avoid having deal with that issue I've created `phoenix-common`:

https://crates.io/crates/phoenix-common

**Comment by jarry-xiao** [comment]
It was published from the `crate` branch

**Comment by kevinheavey** [comment]
Yeah that was what I was referring to by: 
>  If you want you could keep all the exact dependencies in phoenix-v1 even if some of them aren't direct dependencies anymore

**Comment by jarry-xiao** [comment]
Good to close the issue? I'm updating all of the other packages to relax the dependency constraints

**Comment by kevinheavey** [comment]
I still think it would be better to make `phoenix-common` a dependency of `phoenix-v1` and add exact constraints for `spl-token` & co in the `phoenix-v1` Cargo.toml, but up to you since the sdk problem is fixed either way 👍
