### ISSUE TITLE
Swap error

### ISSUE THREAD

**Issue by dannpl** [Ellipsis-Labs/phoenix-v1#35]
It's happened after a swap with Jupiter then i try swap USDC to SOL.

https://solscan.io/tx/3dkhkSNqSD37QJEN4ZKax8DvmQ9PmsffBEWWpzFzJvTBBB8Na2YL54sbX1fnHbd5FfFWDKFsZKubz7oeBk35NWsS

<img width="496" alt="Screenshot 2023-08-17 at 5 17 03 AM" src="https://github.com/Ellipsis-Labs/phoenix-v1/assets/37663993/c960bf9a-0819-4a74-8fe1-eed9ca90749f">

**Comment by jarry-xiao** [comment]
Seems like you already resolved this issue by creating a wSOL Token account.
