### ISSUE TITLE
Updating Solana version

### ISSUE THREAD

**Issue by Fransr24** [Ellipsis-Labs/phoenix-v1#36]
Hey, we are trying to incorporate Phoenix into our program, but we are encoutering a compilation error related to the Solana version. Our solana version (1.14.16) is not compatible Phoenix's version (1.14.9). Could you please update Solana to a compatible version?

**Comment by jarry-xiao** [comment]
You can try using the phoenix-common crate where the constraints are relaxed. Let me know if this works

https://crates.io/crates/phoenix-common
